/**
 * Emits privacy-safe, queryable attempt records for shared chat transports.
 *
 * The correlation value is accepted only as an opaque UUID generated by the
 * first-party client. Arbitrary caller text, message bodies, credentials, and
 * entity identifiers never enter this measurement record.
 */

import { logger } from "../../utils/logger";

export const SHARED_TURN_CORRELATION_HEADER = "X-ElizaOS-Turn-Correlation";
export const SHARED_TURN_ATTEMPT_HEADER = "X-ElizaOS-Turn-Attempt";

const OPAQUE_UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const MAX_RECORDED_ATTEMPT = 100;

export type SharedTurnSurface = "bridge" | "stream";
export type SharedTurnRuntimeKind = "sandbox" | "personal" | "dedicated" | "unresolved";
export type SharedTurnRpcMethod = "message.send" | "status.get" | "heartbeat" | "other" | "invalid";
export type SharedTurnOutcome =
  | "success"
  | "agent_cache_warming"
  | "shared_runtime_cache_warming"
  | "other_error";

export function classifySharedTurnRpcMethod(value: unknown): SharedTurnRpcMethod {
  if (value === "message.send" || value === "status.get" || value === "heartbeat") {
    return value;
  }
  return typeof value === "string" ? "other" : "invalid";
}

export async function classifyBridgeRequestMethod(request: Request): Promise<SharedTurnRpcMethod> {
  const body = (await request
    .clone()
    .json()
    .catch(() => null)) as { method?: unknown } | null;
  return classifySharedTurnRpcMethod(body?.method);
}

export async function classifySharedTurnOutcome(response: Response): Promise<SharedTurnOutcome> {
  if (response.ok) return "success";
  if (response.status !== 503) return "other_error";
  const body = (await response
    .clone()
    .json()
    .catch(() => null)) as { code?: unknown } | null;
  return body?.code === "agent_cache_warming" || body?.code === "shared_runtime_cache_warming"
    ? body.code
    : "other_error";
}

export interface SharedTurnAttemptContext {
  logicalTurn: string | null;
  attempt: number | null;
  attemptKind: "first" | "retry" | "unknown";
}

export function readSharedTurnAttemptContext(headers: Headers): SharedTurnAttemptContext {
  const rawCorrelation = headers.get(SHARED_TURN_CORRELATION_HEADER)?.trim();
  const logicalTurn =
    rawCorrelation && OPAQUE_UUID.test(rawCorrelation) ? rawCorrelation.toLowerCase() : null;
  const rawAttempt = headers.get(SHARED_TURN_ATTEMPT_HEADER)?.trim();
  const attempt = rawAttempt && /^[1-9][0-9]{0,2}$/.test(rawAttempt) ? Number(rawAttempt) : null;
  const boundedAttempt = attempt !== null && attempt <= MAX_RECORDED_ATTEMPT ? attempt : null;
  return {
    logicalTurn,
    attempt: boundedAttempt,
    attemptKind: boundedAttempt === 1 ? "first" : boundedAttempt !== null ? "retry" : "unknown",
  };
}

/**
 * Record one response-header outcome. Warning level is deliberate: cloud info
 * logs are disabled unless VERBOSE_LOGGING is enabled, while this short-lived
 * baseline must include successful first attempts as well as warming failures.
 */
export function recordSharedTurnAttempt(input: {
  headers: Headers;
  surface: SharedTurnSurface;
  rpcMethod: SharedTurnRpcMethod;
  runtimeKind: SharedTurnRuntimeKind;
  status: number;
  outcome: SharedTurnOutcome;
}): void {
  const attempt = readSharedTurnAttemptContext(input.headers);
  logger.warn("[shared-turn baseline] request completed", {
    surface: input.surface,
    rpcMethod: input.rpcMethod,
    runtimeKind: input.runtimeKind,
    status: input.status,
    outcome: input.outcome,
    logicalTurn: attempt.logicalTurn ?? "unavailable",
    attempt: attempt.attempt ?? 0,
    attemptKind: attempt.attemptKind,
  });
}
